@startuml

 package creationImpl {
    class creationImpl.CloudProviderLoader {
         - LOADER : ServiceLoader<CloudProvider>
         + providers(boolean refresh):Iterator<CloudProvider>
         + CloudProviderLoader()
    }
}

@enduml