@startuml

 class exception.ResourceAlreadyExistsException {
        + ResourceAlreadyExistsException(String s)
        + ResourceAlreadyExistsException()
        + ResourceAlreadyExistsException(String message, Throwable cause)
    }
@enduml